[supervisord]
nodaemon=true

[program:frankenphp]
command=frankenphp php-server -r public/ --domain upei-hse.duckdns.org
stderr_logfile=/var/log/supervisor/frankenphp.err.log
sterr_logfile_maxbytes=5MB
sterr_logfile_backups=3
stdout_logfile=/var/log/supervisor/frankenphp.out.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3

[program:ssr]
directory=/app
command=php artisan inertia:start-ssr
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
user=root
numprocs=1
startsecs=1
redirect_stderr=true
stderr_logfile=/var/log/supervisor/ssr.err.log
sterr_logfile_maxbytes=5MB
sterr_logfile_backups=3
stdout_logfile=/var/log/supervisor/ssr.out.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stopwaitsecs=5
stopsignal=SIGTERM
stopasgroup=true
killasgroup=true

[program:queue-worker]
directory=/app
command=php artisan queue:work --daemon --queue=default,scout
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/queue-worker.err.log
sterr_logfile_maxbytes=5MB
sterr_logfile_backups=3
stdout_logfile=/var/log/supervisor/queue-worker.out.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
