<?php

namespace App\StorableEvents\Investigation;

use App\StorableEvents\StoredEvent;

class InvestigationCreated extends StoredEvent
{
    public function __construct()
    {
    }

    public function handle()
    {
        parent::handle(); // TODO: Change the autogenerated stub
    }

    public function react()
    {
        parent::react(); // TODO: Change the autogenerated stub
    }
}
